projects:
  app:
    schemaPath: schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4000
  db:
    schemaPath: generated-schema.graphql
    extensions:
      prisma: prisma.yml
      endpoints:
        default: 'http://localhost:4466/naperg/dev'
